version: '3.1'
services:
  calendar:
    build: .
    image: calendar
    container_name: calendar
    command: npm start
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true